# docker-compose.yml
services:
  dev-db:
    image: postgres:13
    container_name: dev-db
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: nest
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
